version: "3.8"

services:
app:
  build: .
  ports:
    - "3000:3000"
  environment:
    - DATABASE_URL=postgres://user:password@db:5432/eventsourcing
  depends_on:
    db:
      condition: service_healthy

db:
  image: postgres:13
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: eventsourcing
  ports:
    - "5432:5432"
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U user -d eventsourcing"]
    interval: 5s
    timeout: 5s
    retries: 5
